//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceClientDemo.QwaeviszDemoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibraryDemo.Model")]
    public enum Manufacturer : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROVER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOYOTA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OPEL = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarType", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibraryDemo.Model")]
    [System.SerializableAttribute()]
    public partial class CarType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFServiceClientDemo.QwaeviszDemoServiceReference.Dimension DimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EngineCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFServiceClientDemo.QwaeviszDemoServiceReference.Fuel FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer ManufacturerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarName {
            get {
                return this.CarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarNameField, value) != true)) {
                    this.CarNameField = value;
                    this.RaisePropertyChanged("CarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFServiceClientDemo.QwaeviszDemoServiceReference.Dimension Dimension {
            get {
                return this.DimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionField, value) != true)) {
                    this.DimensionField = value;
                    this.RaisePropertyChanged("Dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EngineCapacity {
            get {
                return this.EngineCapacityField;
            }
            set {
                if ((this.EngineCapacityField.Equals(value) != true)) {
                    this.EngineCapacityField = value;
                    this.RaisePropertyChanged("EngineCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFServiceClientDemo.QwaeviszDemoServiceReference.Fuel Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((this.FuelField.Equals(value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((this.ManufacturerField.Equals(value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dimension", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibraryDemo.Model")]
    [System.SerializableAttribute()]
    public partial class Dimension : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fuel", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibraryDemo.Model")]
    public enum Fuel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GASOLINE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIESEL = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://david.bedok.hu/qwaeviszDemoService", ConfigurationName="QwaeviszDemoServiceReference.QwaeviszDemoService")]
    public interface QwaeviszDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/NumberOfCars", ReplyAction="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/NumberOfCarsRespons" +
            "e")]
        int NumberOfCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/AverageEngineCapaci" +
            "ty", ReplyAction="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/AverageEngineCapaci" +
            "tyResponse")]
        double AverageEngineCapacity(WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/FindCar", ReplyAction="http://david.bedok.hu/qwaeviszDemoService/QwaeviszDemoService/FindCarResponse")]
        WCFServiceClientDemo.QwaeviszDemoServiceReference.CarType FindCar(WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer manufacturer, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QwaeviszDemoServiceChannel : WCFServiceClientDemo.QwaeviszDemoServiceReference.QwaeviszDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QwaeviszDemoServiceClient : System.ServiceModel.ClientBase<WCFServiceClientDemo.QwaeviszDemoServiceReference.QwaeviszDemoService>, WCFServiceClientDemo.QwaeviszDemoServiceReference.QwaeviszDemoService {
        
        public QwaeviszDemoServiceClient() {
        }
        
        public QwaeviszDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QwaeviszDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QwaeviszDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QwaeviszDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NumberOfCars() {
            return base.Channel.NumberOfCars();
        }
        
        public double AverageEngineCapacity(WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer manufacturer) {
            return base.Channel.AverageEngineCapacity(manufacturer);
        }
        
        public WCFServiceClientDemo.QwaeviszDemoServiceReference.CarType FindCar(WCFServiceClientDemo.QwaeviszDemoServiceReference.Manufacturer manufacturer, string name) {
            return base.Channel.FindCar(manufacturer, name);
        }
    }
}
