//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNBWebServiceConsoleClient.MNBArfolyamServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MNBArfolyamServiceReference.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetInfoResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse GetInfo(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse> GetInfoAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrentExchangeRatesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name startDate from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse GetExchangeRates(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse> GetExchangeRatesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetDateIntervalResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse GetDateInterval(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse> GetDateIntervalAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrenciesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse GetCurrencies(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse> GetCurrenciesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since element name currencyNames from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse GetCurrencyUnits(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoRequestBody {
        
        public GetInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequestBody Body;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody {
        
        public GetCurrentExchangeRatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponseBody Body;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrentExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentExchangeRatesResult;
        
        public GetCurrentExchangeRatesResponseBody() {
        }
        
        public GetCurrentExchangeRatesResponseBody(string GetCurrentExchangeRatesResult) {
            this.GetCurrentExchangeRatesResult = GetCurrentExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string startDate, string endDate, string currencyNames) {
            this.startDate = startDate;
            this.endDate = endDate;
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateInterval", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequestBody Body;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDateIntervalRequestBody {
        
        public GetDateIntervalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponseBody Body;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetDateIntervalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateIntervalResult;
        
        public GetDateIntervalResponseBody() {
        }
        
        public GetDateIntervalResponseBody(string GetDateIntervalResult) {
            this.GetDateIntervalResult = GetDateIntervalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencies", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequestBody Body;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrenciesRequestBody {
        
        public GetCurrenciesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponseBody Body;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrenciesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrenciesResult;
        
        public GetCurrenciesResponseBody() {
        }
        
        public GetCurrenciesResponseBody(string GetCurrenciesResult) {
            this.GetCurrenciesResult = GetCurrenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnits", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequestBody Body;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currencyNames;
        
        public GetCurrencyUnitsRequestBody() {
        }
        
        public GetCurrencyUnitsRequestBody(string currencyNames) {
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponseBody Body;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyUnitsResult;
        
        public GetCurrencyUnitsResponseBody() {
        }
        
        public GetCurrencyUnitsResponseBody(string GetCurrencyUnitsResult) {
            this.GetCurrencyUnitsResult = GetCurrencyUnitsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap>, MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetInfo(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequestBody();
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetInfoAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoResponse> GetInfoAsync() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetInfoRequestBody();
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrentExchangeRates(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public string GetCurrentExchangeRates() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequestBody();
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.Body.GetCurrentExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrentExchangeRatesRequestBody();
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetExchangeRates(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string startDate, string endDate, string currencyNames) {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetExchangeRatesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesResponse> GetExchangeRatesAsync(string startDate, string endDate, string currencyNames) {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetDateInterval(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public string GetDateInterval() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequestBody();
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.Body.GetDateIntervalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetDateIntervalAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalResponse> GetDateIntervalAsync() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetDateIntervalRequestBody();
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrencies(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public string GetCurrencies() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequestBody();
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.Body.GetCurrenciesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrenciesAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesResponse> GetCurrenciesAsync() {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrenciesRequestBody();
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrencyUnits(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public string GetCurrencyUnits(string currencyNames) {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse retVal = ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.Body.GetCurrencyUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse> MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(string currencyNames) {
            MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest inValue = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequest();
            inValue.Body = new MNBWebServiceConsoleClient.MNBArfolyamServiceReference.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            return ((MNBWebServiceConsoleClient.MNBArfolyamServiceReference.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
    }
}
